broker:
  image: 'prologic/mosquitto:latest'
  ports:
    - '1883:1883'
database:
  image: 'tutum/mongodb:latest'
  environment:
    - MONGODB_PASS=maddymaddy2019

# Uncomment if you want to expose the MongoDB port directly
# If you're using the API interface (highly recommended) then you can 
# safely leave this commented out 
#  ports:
#    - '27017:27017'

nightscout:
  image: 'nightscout/cgm-remote-monitor-development:latest'
  environment:
    - API_SECRET=maddymaddy2019
    - 'MONGO_CONNECTION=mongodb://admin:{{** CHANGE ME **}}@database/admin'
    - 'MQTT_MONITOR=mqtt://maddymaddy2019@broker'
    - PORT=1337
  links:
    - broker
    - database
  ports:
    - '1337:1337'
